name: Test

on:
  workflow_dispatch:

jobs:
  Step1:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: hi
        run: |
          echo "Hi"
      - name: wow
        run: |
          echo "will fail"
          exit 1
      - name: oops
        run: |
          echo "oops"
          exit 1

  Step2:
    runs-on: ubuntu-latest
    needs: [Step1]
    steps:
    - name: bye
      run: |
        echo "Bye"

  
