on:
  workflow_dispatch:


jobs:
  test:
    name: testing-for-${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20, 22] # This will create 3 parallel jobs
    steps:
      - uses: actions/checkout@v4
      - name: print
        run: |
          echo "HI ${{ matrix.node-version }}"
          if [[ "${{ matrix.node-version }}" == "18" ]]; then
            echo "OOPS"
            exit 1
          fi

  result:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: bye
        run: |
          echo "BYE"
