name: manual test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Notice
        run: |
          echo "::notice ::This is notice1\nThis is notice2\nThis is notice3"