name: manual test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Notice
        run: |
          echo "::notice file=myfile.sh,line=1::This is notice1%0AThis is notice2%0AThis is notice3"
