on:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20, 22] # This will create 3 parallel jobs
    steps:
      - uses: actions/checkout@v4
      - name: print
        runs: |
          echo "HI ${{ matrix.node-version }}"
